Import library

In [1]:
import pandas as pd

Load Dataset

In [40]:
df = pd.read_csv("aircraft_accident_data_1991_2023.csv", encoding="euc_kr")
df.rename(columns=df.iloc[0], inplace=True)
df.set_index('년(Annual)', inplace=True)
df.drop('년(Annual)', axis=0, inplace=True)
df.fillna(0)

          조종사과실 기체이상 기상악화 원인불명 기타  계   사망   부상    계
년(Annual)
1991          3    0    0    0  0  3    0    3    3
1992          2    1    0    0  0  3    1   11   12
1993          2    1    0    0  0  3   73   47  120
1994          1    0    1    0  0  2    0   10   10
1995          0    0    0    0  0  0    0    0    0
1996          2    0    0    0  0  2    1    1    2
1997          2    0    0    0  2  4  232   26  258
1998          2    0    0    0  2  4    0   70   70
1999          2    1    0    0  0  3   12  105  117
2000          3    0    0    0  0  3    0    1    1
2001          2    1    2    0  0  5    9    8   17
2002          4    0    0    0  0  4    2    1    3
2003          2    0    0    0  3  5    2    3    5
2004          2    1    0    0  0  3    2    1    3
2005          2    0    0    0  1  3    1    4    5
2006          5    0    0    0  0  5    0    0    0
2007          0    1    0    0  0  1    0    4    4
2008          2    0    0    0  1  3    0   16   16
2009          4    1    0    0  0  5    5    0    5
2010          1    4    0    0  0  5    1    0    1
2011          5    0    0    0  2  7   10    4   14
2012          2    1    2    0  0  5    1    4    5
2013          7    0    1    0  1  9   10  201  211
2014          3    0    0    0  0  3    5    5   10
2015          1    0    0    0  0  1    0   20   20
2016          4    1    0    0  3  8    9    0    9
2017          4    1    0    0  0  5    2    4    6
2018          2    0    0    0  1  3    1    2    3
2019          0    0    2    0  3  5    7    3   10
2020          0    0    2    0  2  4    3    3    6
2021          0    0    1    0  1  2    0    1    1
2022          0    0    0    0  6  6    8    1    9
2023          0    0    0    0  6  6    3    2    5